### ISSUE TITLE
Helpful

### ISSUE THREAD

**Issue by asyncthreading** [iChaoticSoldier/FactionsPro-v1.7.9#1]

**Comment by iChaoticSoldier** [comment]
Yes just email me iChaoticSoldier@gmail.com

**Comment by VCraftMCPE** [comment]
YOU DIDNT MAKE THIS-
this is the original FactionsPro
modified by Panda998 add the real authors nanes

**Comment by iChaoticSoldier** [comment]
For your information i do modified it with a help of my friends in LifeBoat
they are good developers i do putted the commands and they did the function
arrays

**Comment by iChaoticSoldier** [comment]
And for your sake there is alot of modified factionspro by some local
developers
